behave-lib/include/cpp/sig-adapters/SIGSpot.cpp

Closes BHP1-1180
1. Open Local App and rerun worksheekt: 
[Spotting-Torching-Trees.zip](https://github.com/user-attachments/files/18950245/Spotting-Torching-Trees.zip)
2. Ensure the results for a "Surface" "Fire Type" has a value instead of a "-"

[BHP1-1180] Fix Max Spot Distance from Torching Trees

---

development/migrations/2025_02_24_add_mising_fuel_moisture_conditionals.clj

-------
Closes BHP1-1096
1. Open local VMS and run migration script in ns `migrations.2025-02-24-add-mising-fuel-moisture-conditionals`
2. Open local app and sync vms
3. Create Surface Worksheet
4. Select outputs: Flame Length
5. Navigate to Inputs > Fuel Model
7. Select "V-Ha/111"
8. Navigate to "Fuel Moisture". Select "Individual Size Class"
9. Ensure you see:
- 1-h Fuel Moisture
- 10-h Fuel Moisture
- Live Herbaceous
- Live Woody
10. Repeat steps 7 - 9 for "V-Hb/110" and "V-MH/115"

[BHP1-1096] Add Missing Fuel Moisture Conditionals

---

development/migrations/2025_03_13_rearrange_group_variables_crown_size_submodule.clj
projects/behave/src/cljs/behave/wizard/views.cljs

-------
Closes BHP1-1211
1. Open local VMS and run migration script in ns `migrations.2025-03-13-rearrange-group-variables-crown-size-submodule`
2. Open local App and open worksheet: 
[BHP1-1211-surface-crown.zip](https://github.com/user-attachments/files/19236940/BHP1-1211-surface-crown.zip)
3. Navigate to outputs > Size
4. Ensure the page now looks as such:
5. Rerun worksheet and ensure completion and there are values for the selected outputs

[BHP1-1211] Update Crown Size Submodule

---

projects/behave/src/cljs/behave/utils.cljs

-------
Closes BHP1-1128
1. Open local app and create a Surface run
2. Navigate to Inputs > Wind and Slope
3. Select "Wind Measured At" = "20-ft"
4. Under "Wind Adjustment Factor - User Input" click "Range Selector"
5. Input test cases and ensure the values computed and the application does not hang:
Test case 1:
From: 0
To: 1
steps: 0.2
Test case 2:
From: 1
To: 0
steps: -0.2

[BHP1-1128] Fix Range Selector when using Negative Steps

---

development/migrations/2025_03_18_update_mortality_tree_species_names.clj

Closes BHP1-1232
1. Open local VMS and run migraiton script in ns `migrations.2025-03-18-update-mortality-tree-species-names`
2. Navigate to "List" > "MortalitySpeciesMasterList"
3. Click "Edit"
4. Ensure both the names and the translation has been updated to the format: Latin / Code (common-name)

[BHP1-1232] Update Species Label

---

development/migrations/2025_03_18_update_mortality_tree_species_tags.clj

Closes BHP1-1233
1. Open Local VMS and run migration script in ns `migrations.2025-03-18-update-mortality-tree-species-tags`
2. Open local App and sync vms
3. Create a Surface and Mortality Worksheet
4. Navigate to Inputs > Fuel Model > Fuel Model.
5. Click "Select More" and ensure filter tags now uses spaces instead of "-"
7. Navigate to Inputs > Tree Characteristics > Tree Species
5. Click "Select More" and ensure filter tags now uses spaces instead of "-"

[BHP1-1233] Update Tree Species and Fuel Model Tags

---

projects/behave/src/cljs/behave/components/results/graphs.cljs
projects/behave/src/cljs/behave/wizard/views.cljs
projects/behave/src/cljs/behave/worksheet/subs.cljs

Closes BHP1-1127
1. Open this worksheet: 
[BHP1-1127-PR.zip](https://github.com/user-attachments/files/19437574/BHP1-1127-PR.zip)
2. Navigate to "Results Settings" page
3. Ensure that "Fire Type" no longer shows in the Graph Settings
4. Navigate to "Results" page
5. Ensure "Fire Type" output graph no longer shows.

[BHP1-1127] Hide Discrete Output Graphs and settings

---

projects/behave/src/cljs/behave/components/sidebar.cljs

-------
Closes BHP1-1207
1. Open local App and create a Surface + Crown worksheet
2. Navigate to Outputs page.
3. Refresh the page and ensure the side bar modules order should be Surface then Crown

[BHP1-1207] Fix Sidebar Module Order

---

projects/behave/resources/public/css/app-style.css
projects/behave/src/cljs/behave/client.cljs
projects/behave/src/cljs/behave/help/events.cljs
projects/behave/src/cljs/behave/help/views.cljs

-------
* Adds formatting for tables in the Help sidebar (bold table headers, borders for cells).
* Adds new "Table Viewer" to view tables in a larger modal window.
* Fixes images to no longer take over the whole screen.
* Adds ability to click on the background of the modal to close it.
Closes [BHP1-1224](https://sig-gis.atlassian.net/browse/BHP1-1224)
1. Open a new Surface and Crown worksheet
2. Click on the images in the Help Area
3. Verify that Image does not exceed the window size
3. Verify that clicking on the background closes the modal
1. Open a new Surface worksheet
2. Scroll down in the Help Area to the table
3. Verify that the table now has borders, distinct headers
1. Open a new Surface worksheet
2. Scroll down in the Help Area to the table
3. Verify that upon hovering over …

Fix Help Tables, Fix Image Sizes, Add new Table Viewer

---

projects/behave/src/cljs/behave/help/views.cljs

-------
Fix HTML encoded elements (e.g. `&lt;`, `&amp;`)
Closes [BHP1-1224](https://sig-gis.atlassian.net/browse/BHP1-1224)
1. Open a Surface worksheet
2. Select Heading / Rate of Spread as outputs
3. Go to Inputs, enter a fuel model
4. Go to Fuel Moisture, scroll to find `"1 HR Fuel < 0.25"`
5. Verify that it no longer shows `&lt;`
[BHP1-1224]: https://sig-gis.atlassian.net/browse/BHP1-1224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTML-Decode elmements after Hiccup conversion

---

projects/behave/src/cljs/behave/components/sidebar.cljs

-------
EOM
Closes BHP1-1171
1. Open a Worksheet with Surface & Crown
2. Clicking on either Surface or Crown icon in the left Module panel
does not change your place in the Worksheet

[BHP1-1171] Remove Click Functionality for Modules in Sidebar

---

projects/behave/src/cljs/behave/worksheet/views.cljs

-------
Closes BHP1-1215
1. Open App
2. Select "Guided Workflow"
3. Navigate to "Worksheet Selection" Page
4. Ensure the input field for worksheet name no longer shows

[BHP1-1215] Remove Worksheet Name

---

development/migrations/2025_03_31_add_version_warning_translations.clj
projects/behave/resources/public/css/app-style.css
projects/behave/src/cljs/behave/store.cljs
projects/behave/src/cljs/behave/worksheet/subs.cljs
projects/behave/src/cljs/behave/worksheet/views.cljs

Closes BHP1-1225
1. Create file: `projects/behave/resources/version.edn` if it does not already exist.
``` clojure
{:version "v7.0.0-alpha-test"}
```
2. Ensure that upon selecting this worksheet for import (you do not need to click next) a warning pops up for mismatched version: [bad-version.zip](https://github.com/user-attachments/files/19556163/bad-version.zip)
3. Click "Browse" and change the worksheet to this one: [alpha-test.zip](https://github.com/user-attachments/files/19556164/alpha-test.zip)
4. Ensure the warning now disappears.

[BHP1-1225] Add Mismatched Version Warning on Import Page

---

bases/behave_schema/src/behave/schema/domain.cljc
projects/behave/src/cljs/behave/components/unit_selector.cljs
projects/behave_cms/src/cljs/behave_cms/client.cljs
projects/behave_cms/src/cljs/behave_cms/components/entity_form.cljs
projects/behave_cms/src/cljs/behave_cms/domains/subs.cljs
projects/behave_cms/src/cljs/behave_cms/domains/views.cljs

- Allows users to filter the units for a particular domain to display
only a subset of units.
Closes BHP1-1213
1. Pull down latest VMS data from Dev
2. Start VMS & App
3. Open VMS > Variable Domains > Terrain & Spotting >Slope & Elevation
4. Select under `Filtered Units`: Feet, Miles, Kilometers, Meters (see
screenshot 1)
5. Sync App
6. Open "Slope Tool" > Slope from Map Measurements
7. Verify that only the selected units are available in the dropdown
(see screenshot 2)

[BHP1-1213] Filter unit selections with :domain/filtered-units

---

projects/behave/src/clj/behave/views.clj
projects/behave/src/cljs/behave/print/views.cljs

-------
Hides banner in PDF view and in Wizard view.
Closes BHP1-1259
1. Ensure there is an "announcement.txt" in `resources/public` folder
2. Open local app
3. Ensure a banner shows
4. Create a worksheet
5. Print worksheet, ensure a banner does not show now.

[BHP1-1259] Hide Banner in PDF and Wizard pages

---

projects/behave/src/clj/behave/views.clj
projects/behave/src/cljs/behave/print/views.cljs
projects/behave/src/cljs/behave/worksheet/events.cljs

-------
Application would not start if a version.edn did not exist.
Closes BHP1-1263
1. Ensure you do not have a `resources/version.edn` file.
2. Open Application
3. Ensure it opens correctly
4. Ensure the title in the tab shows "BehavePlus" and not "BehavePlus (null)"

[BHP1-1263] Fix Application not Starting without version.edn

---

development/migrations/2025_04_07_add_disclaimer_translation.clj
projects/behave/resources/public/css/app-style.css
projects/behave/src/cljs/behave/client.cljs
projects/behave/src/cljs/behave/settings/subs.cljs
projects/behave/src/cljs/behave/wizard/events.cljs
projects/behave/src/cljs/behave/worksheet/views.cljs

-------
1. Adds a disclaimer pop up to the home page of the application
2. Caches state of disclaimer pop up in the browser's cache
Closes BHP1-1260
1. Open local VMS and run migration in ns `migrations.2025-04-07-add-disclaimer-translation`
2. Open local App and sync vms
3. Refresh Screen. Ensure there is a pop up modal for the disclaimer.
4. Close the modal and refresh page
5. Ensure the modal does not pop up now.
6. Click the "disclaimer" button at the bottom of the page.
7. Ensure the modal pops up again.

[BHP1-1260] Add Disclaimer

---

projects/behave/src/cljs/behave/components/toolbar.cljs

-------
Closes BHP1-1269
1. Open App, Ensure the zoom out, zoom in, and search bar is no longer showing in the toolbar

[BHP1-1269] Hide Unused Toolbar Icons for now

---

bases/behave_components/resources/public/css/styles.css
bases/behave_components/src/cljs/behave/components/inputs.cljs
bases/behave_components/src/cljs/behave/stories/multi_select_input_stories.cljs
bases/behave_schema/src/behave/schema/language.cljc
bases/behave_schema/src/behave/schema/list.cljc
components/schema_migrate/src/schema_migrate/core.clj
components/schema_migrate/src/schema_migrate/interface.clj
development/migrations/2025_04_05_migrate_list_tags.clj
projects/behave/src/cljs/behave/components/input_group.cljs
projects/behave/src/cljs/behave/wizard/subs.cljs
projects/behave_cms/src/cljc/behave_cms/routes.cljc
projects/behave_cms/src/cljs/behave_cms/client.cljs
projects/behave_cms/src/cljs/behave_cms/components/entity_form.cljs
projects/behave_cms/src/cljs/behave_cms/languages/subs.cljs
projects/behave_cms/src/cljs/behave_cms/lists/subs.cljs
projects/behave_cms/src/cljs/behave_cms/lists/views.cljs
projects/behave_cms/src/cljs/behave_cms/tags/views.cljs

---
* Creates new `:tag-set/*`, `:tags/*` schema to hand both filter tags
and color/category tags
* Creates new `/tags` page in the VMS the create, update Tag Sets/Tags
* Updates multi-select component to allow `filter-tags` and
`color-tags` to be passed in, rather than pulling from the options.
* Updates app to use new tags, including updating proper subscriptions
* Adds migration to migrate existing tags
Closes [BHP1-1238](https://sig-gis.atlassian.net/browse/BHP1-1238)
- [z] Code passes linter rules (`clj-kondo --lint components/**/src bases/**/src projects/**/src`)
- [z] Feature(s) work when compiled (`clojure -M:compile-cljs`)
1. Pull down latest, start App/VMS
2. Run Migration `migrations.2025-04-05-migrate-list-tags`
3. Verify that the following Tag Sets exist in the VMS:
* Fuel …

[BHP1-1238] Add Tag-Set/Tags structure to VMS to enable Multi-tags sorting

---

bases/behave_components/src/cljs/behave/components/inputs.cljs

-------
Multi select errors out on a second selection.
The issue is with the selections atom. Since some selections don't have color-tag it cant compare it inside a sorted-set. Fix here is to remove the color tag from the selections, this is not needed to keep track of what is being selected.
Closes BHP1-1277
1. Open a surface worksheet and navigate to inputs page
2. Select at least 2 or more fuel models. Ensure the application does not go blank on the second selection

[BHP1-1277] Fix Multi Select

---

projects/behave/src/cljs/behave/components/results/inputs/views.cljs
projects/behave/src/cljs/behave/components/review_input_group.cljs
projects/behave/src/cljs/behave/vms/subs.cljs
projects/behave/src/cljs/behave/worksheet/subs.cljs

-------
Closes BHP1-1280
1. Create a Surface worksheet
2. Select Outputs:
- Direciton Mode > Heading
- Surface Fire > Rate of Spread
3. Navigate to Inputs > Fuel Model
4. Select Multiple Fuel models in random order.
5. Complete the worksheet and navigate to Review page
6. Ensure Fuel Model Codes are ordered as expected
7. Run the worksheet
8. Navigate to results page.
9. Ensure Fuel Model Codes are ordered as expected in the inputs table

[BHP1-1280] Fix Multi Discrete Input order in Review and Result Page

---

projects/behave/src/cljs/behave/wizard/subs.cljs
projects/behave/src/cljs/behave/wizard/views.cljs
projects/behave/src/cljs/behave/worksheet/events.cljs

-------
Closes BHP1-1286
1. Open local app and create a worksheet
2. Fill in worksheets but with no multi valued inputs
3. Run worksheet
4. Navigate to Settings page
5. Ensure the graph settings DO NOT show (this should be as before)
6. Go back to inputs and change one to a multi valued input
7. Re run worksheet and navigate to settings page
8. Ensure the graph settings section is now shown and that it is enabled by default (new behavior).

[BHP1-1286] Default Graph Settings to True When Needed

---

projects/behave/src/cljs/behave/solver/table.cljs
projects/behave/src/cljs/behave/wizard/subs.cljs
projects/behave/src/cljs/behave/worksheet/subs.cljs

The laziness was causing headers group variables to be omitted from the map of headers. Using `doseq` to fix this.
Closes BHP1-1326
1. Open this worksheet re-run: 
[Surf&Contain_Resources.zip](https://github.com/user-attachments/files/20511644/Surf.Contain_Resources.zip)
2. Open this worksheet re-run:
[Surface&Crown.zip](https://github.com/user-attachments/files/20511646/Surface.Crown.zip)

[BHP1-1326] Fix Hanging Compute

---

development/migrations/2025_06_23_rename_tools_to_calculators.clj
projects/behave/src/cljs/behave/components/sidebar.cljs
projects/behave/src/cljs/behave/tool/views.cljs

-------
1. Rename "Tools" to "Calculators":
- Main menu should say Calculators & Settings
- Button should say Calculators (plural)
- Header in the selection window should say Select a Calculator
- Close button says Close Calculator
2. Rename tool names for clarity:
- Ignite → Probability of Ignition
- 1-HR Fuel Moisture → 1-Hour Fuel Moisture
- Slope Tool → Slope from Map Measurements
Closes BHP1-1313
1. Start VMS
2. Run migration `migrations.2025-06-23-rename-tools-to-calculators`
3. Start App, Sync
4. Verify that translations have been updated to use 'Calculators'
5. Open 'Calculators', verify that calculators have been renamed

[BHP1-1313] Rename 'Tools' to 'Calculators'

---

projects/behave/src/cljs/behave/components/toolbar.cljs

-------
VMS Button component still showing (with no label/icon) when specified in the config. This should completely remove the component.
Closes BHP1-1336
1. Update config with `{:client {:jar-local? true}}`
2. Open local app and ensure there is no button component after the print icon

[BHP1-1336] Remove Vms Sync Button Component Completely

---

projects/behave/src/cljs/behave/components/review_input_group.cljs
projects/behave/src/cljs/behave/wizard/views.cljs

-------
- Review page was not showing all inputs, this fixes it.
Closes BHP1-1348
1. open this worksheet: 
[BHP1-1330.zip](https://github.com/user-attachments/files/21026334/BHP1-1330.zip)
2. Ensure all necessary inputs show in review page

[BHP1-1330] fix review page from missing inputs

---

components/schema_migrate/src/schema_migrate/core.clj
development/migrations/2025_07_11_update_contain_search_table_name.clj

-------
Closes BHP1-1360
1. Open local vms and run migration in ns `migrations.2025-07-11-update-contain-search-table-name`
2. in VMS Navigate to Contain > Search Tables
3. Ensure the name is updated
4. Sync App to vms
5. Open this worksheet: 
[BHP1-1360.zip](https://github.com/user-attachments/files/21186814/BHP1-1360.zip)
6. Ensure the table name has been updated.

[BHP1-1360] Update Contain Search Table Name

---

bases/behave_schema/src/behave/schema/pivot_table.cljc
components/schema_migrate/src/schema_migrate/interface.clj
development/migrations/2025_05_02_remove_duplicate_output_variable_translation.clj
development/migrations/2025_06_30_update_mortality_pivot_table.clj
projects/behave/src/cljs/behave/worksheet/subs.cljs
projects/behave_cms/src/cljs/behave_cms/components/common.cljs
projects/behave_cms/src/cljs/behave_cms/submodules/subs.cljs
projects/behave_cms/src/cljs/behave_cms/submodules/views.cljs

-------
Use `:pivot-table/order` for determining the order of columns in the
Pivot Table
Closes BHP1-1325
1. Start VMS, run `migrations.2025-06-30-update-mortality-pivot-table`
2. Sync App, run Surface + Mortality with at least 3 Mortality
Species, go to outputs
3. Verify that the order of columns is:
- Mortality Tree Species
- Equation Type
- CVS or CLS
4. Verify that the title of the Pivot Table is "Equation Type"

[BHP1-1325] Update VMS, App to use `:pivot-column/order`

---

projects/behave/src/cljs/behave/components/results/matrices.cljs
projects/behave/src/cljs/behave/vms/subs.cljs
projects/behave/src/cljs/behave/wizard/views.cljs

-------
Closes BHP1-1322
1. Open this worksheet and ensure there is a result table for non directional outputs: 
[BHP1-1322.zip](https://github.com/user-attachments/files/21477698/BHP1-1322.zip)

[BHP1-1322] Always Show Non Directional Output matrices

---

development/migrations/2025_07_25_spot_torching_trees_action.clj
projects/behave/src/cljs/behave/solver/core.cljs

Fixes issue where Torching Trees/Active Crown Fire would not be able
to be run solo (without Surface/Crown modules).
1. Adds migration `migrations.2025-07-25-spot-torching-trees-action`
2. Updates solver to not overwrite inputs. Fixes issue where
conditionally set inputs were being overwritten by Surface/Crown
module even though the module was not being run.
Closes BHP1-1356
1. Run migration `migrations.2025-07-25-spot-torching-trees-action`
2. Sync Dev, run the following worksheet:
3. Verify that the output for Max Spotting from Torching Trees is
greater than 0

[BHP1-1356] Fix Solo running Torching Trees/Active Crown Spot Dist.

---

projects/behave/src/cljs/behave/wizard/subs.cljs

-------
Closes BHP1-1338
1. Open this worksheet:  [Surface_NoTable_Range1h (1).zip](https://github.com/user-attachments/files/21606448/Surface_NoTable_Range1h.1.zip)
2. Ensure Output table is displayed

[BHP1-1338] Fix Missing Output Table

---

projects/behave/src/cljs/behave/components/results/table.cljs

-------
Closes BHP1-1397
1. Sync to dev vms. (I've updated translations for the map units header)
2. Open this worksheet and navigate to results: [Map_units_bug.zip](https://github.com/user-attachments/files/21971784/Map_units_bug.zip)
3. Ensure the header names for map unit columns are updated
5. Ensure flame length outputs do not have map unit columns

[BHP1-1397] Update Map Units header

---

development/migrations/2025_09_17_update_ssd_tool.clj

-------
EOM
Closes [BHP1-1419](https://sig-gis.atlassian.net/browse/BHP1-1419)
1. Run `migrations.2025-09-17-update-ssd-tool`
2. Sync
3. Verify that tool name is updated
[BHP1-1419]: https://sig-gis.atlassian.net/browse/BHP1-1419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BHP1-1419] Update Safe Separation Distance tool name

---

development/migrations/2025_10_01_update_ssd_colors.clj
projects/behave_cms/src/cljs/behave_cms/tags/views.cljs

-------
1. Migration to update the Safety Conditions
2. Fixes the Color Tag editor
Closes BHP1-1436
1. Run migration `migrations.2025-10-01-update-ssd-colors`, sync
2. Run the "Safe Separation Distance" tool with:
- Burning Condition/Slope Class/Wind Speed Class: Moderate
- Vegetation Height: 10 ft
3. Verify that the color for "Moderate" is a gold yellow
4. Run the "Safe Separation Distance" tool with:
- Burning Condition: Extreme
- Slope Class: Steep
- Wind Speed Class: High
- Vegetation Height: 10 ft
3. Verify that the color for "Extreme" is a bronze red

[BHP1-1436] Updates Safey Condition Colors, fix tag color editing

---

bases/behave_components/src/cljs/behave/components/inputs.cljs

Closes BHP1-1143
1. Open surface+contain worksheet in guided mode
2. Select Outputs:
- Fire Behavior > Direction Mode > Heading
- Fire Behavior > Surface Fire > Rate of Spread
3. Navigate to Inputs > Fuel Model
4. Ensure Fuel Model updates stick on refresh
5. Navigate to Inputs > Suppression and select Contain Mode > "Calculate Minimum Production Rate Only"
6. Navigate to Inputs > Fuel Model
7. Ensure Fuel Model updates stick on refresh
6. Repeat steps 1 - 5 for standard workflow (make sure to test on click and on keypress (i.e. enter) behaviors)

[BHP1-1444] Fix Fuel Models Selection not Saving

---

projects/behave/src/cljs/behave/components/review_input_group.cljs

-------
Closes BHP1-1443
1. Open this worksheet and navigate to review page:
[behave7-68dec956-3819-420b-9dba-a89893700cc9.zip](https://github.com/user-attachments/files/22665740/behave7-68dec956-3819-420b-9dba-a89893700cc9.zip)
2. Ensure the resource name is in the text box:

[BHP1-1443] fix Resource name in review page

---

.github/workflows/bump-version.yml
bases/behave_schema/src/behave/schema/worksheet.cljc
projects/behave/resources/public/css/app-style.css
projects/behave/src/cljs/behave/components/unit_selector.cljs
projects/behave/src/cljs/behave/settings/events.cljs
projects/behave/src/cljs/behave/settings/subs.cljs
projects/behave/src/cljs/behave/settings/views.cljs
projects/behave/src/cljs/behave/solver/core.cljs
projects/behave/src/cljs/behave/solver/queries.cljs
projects/behave/src/cljs/behave/tool/events.cljs
projects/behave/src/cljs/behave/tool/solver.cljs
projects/behave/src/cljs/behave/tool/subs.cljs
projects/behave/src/cljs/behave/wizard/subs.cljs
projects/behave/src/cljs/behave/worksheet/events.cljs
projects/behave/src/cljs/behave/worksheet/subs.cljs
projects/behave/test/cljs/behave/worksheet_events_test.cljs
projects/behave_cms/src/cljs/behave_cms/domains/views.cljs

Closes BHP1-1246
1. Open local App and Navigate to Settings
2. Ensure there is now an option to switch units system between English and Metric
3. Expand an accordion
4. Change units to "Metric" and ensure "units" column all change accordingly
5. Create a worksheet and ensure any "continuous" inputs (i.e. wind speed) is defaulted to it's metric unit
7. Run the worksheet and ensure results are also in metric
8. Change units system back to "English" and re-run worksheet
9. Ensure the inputs and results are now in "English" units
10. Open a tools and repeat steps 4-9

[BHP1-1246] Add Global Units Settings for English and Metric
