firelab/behave-app

projects/behave/src/cljs/behave/components/input_group.cljs
Closes BHP1-1173
1. Open local vms
2. Create surface + contain run
3. Navigate to Inputs > "Suppression" > "Resource"
4. Input a "Resource Name"
5. Refresh page, and ensure the full name persists
=> [BHP1-1173] Fix Resource Name In Contain

development/migrations/2025_01_31_update_fuel_moisture_conditionals.clj
Closes BHP1-1097 and BHP1-1096
1. Open Local VMS
2. Run migration in ns `migrations.2025-01-31-update-fuel-moisture-conditionals`
3. Open Local App and sync vms
4. Create Surface Worksheet
5. Navigate to Inputs > Fuel Model Code
6. Select "V-MMa/155" (this should be available now)
7. Navigate to Inputs > "Fuel Moisture" and select "Individual Size Class"
8. You should now only see these inputs:
- 1-h Fuel Moisture
- 10-h Fuel Moisture
- Live Woody Fuel Moisture
=> [BHP1-1097] Update Fuel Moisture Conditionals

projects/behave/src/cljs/behave/components/results/matrices.cljs
Closes BHP1-1169
1. open this worksheet:
[Mortality_Dupilcate_Results (1).zip](https://github.com/user-attachments/files/18663720/Mortality_Dupilcate_Results.1.zip)
2. Re-run and navigate to results page
3. Ensure that "Crown Length Scorched (ft)" result matrix no longer shows
1. open this worksheet: 
[Mortality_Duplicate_Results_Single-Range.zip](https://github.com/user-attachments/files/18663716/Mortality_Duplicate_Results_Single-Range.zip)
2. Re-run and navigate to results page
3. Ensure that output columsn "CVSorCLS" and "Equation Type" no longer show in the result matrix.
=> [BHP1-1169] Hide Outputs that are Already Shown in Pivot Table

projects/behave/resources/public/css/app-style.css, projects/behave/src/cljs/behave/components/input_group.cljs
-------
Closes BHP1-1175
1. Open Local App
2. Create Surface + Contain worksheet
3. Navigate to Inputs > Suppression
4. Click "Add Resource"
5. Fill out Resource and refresh to ensure it persists
7. Click "Delete" button
6. Refresh page to ensure the resource is now deleted and persists.
=> [BHP1-1175] Add Delete Button to Repeat Inputs on Inputs page

projects/behave/src/cljs/behave/components/toolbar.cljs, projects/behave/src/cljs/behave/wizard/views.cljs
Closes BHP1-1210
1. Sync to dev VMS
2. Create and complete a run
3. Ensure Texts are updated as per Jira ticket.
=> [BHP1-1210] Update Header and Progress bar text

projects/behave/src/cljs/behave/wizard/views.cljs
-------
Closes BHP1-1194
1. Open this worksheet: [test_display_units_settings_page.zip](https://github.com/user-attachments/files/19213961/test_display_units_settings_page.zip)
2. Navigate to "Results Settings" page
3. Ensure there are now units shown after the output/input variable name
=> [BHP1-1194] Add Units to Settings Page

projects/behave/resources/public/css/app-style.css, projects/behave/src/cljs/behave/components/results/matrices.cljs
-------
Adds an X background image to `.table-cell__shaded` class
=> Add X background image.

projects/behave/resources/public/css/app-style.css
=> Fixes print view for shaded table cells, increases contrast

projects/behave/src/cljs/behave/worksheet/events.cljs
-------
Closes BHP1-1230
1. Open this worksheet: [BHP1-1230-PR.zip](https://github.com/user-attachments/files/19455790/BHP1-1230-PR.zip)
2. Navigate to "Results Settings" page
3. Re toggle "Display Graph Results"
4. Ensure "Wind Speed" is defaulted as the "X axis Variable"
=> [BHP1-1230] Update Default Graph Settings

projects/behave/src/cljs/behave/settings/views.cljs
Closes BHP1-1242
1. Open local app and navigate to Settings > Fuel Model Selection.
2. Ensure the text now reads "Comming Soon!"
3. Do the same for Settings > Moisture Scenario Selection
=> [BHP1-1242] Update to Comming Soon text

projects/behave/resources/public/css/app-style.css, projects/behave/src/cljs/behave/client.cljs, projects/behave/src/cljs/behave/worksheet/views.cljs
-------
Closes BHP1-1267
1. Open app and create worksheet
2. Navigate to outputs page
3. Click "Disclaimer" link and Ensure you are not navigated away from the page.
=> [BHP1-1267] update link to span

projects/behave/src/cljs/behave/components/toolbar.cljs
-------
Closes BHP1-1268
1. Open local App
2. Navigate to Module Selection page
3. Click Home icon in the top toolbar
4. Ensure you are navigated to the Home page.
=> [BHP1-1268] Update Home Icon to Navigate to Home Page

projects/behave/src/cljs/behave/components/input_group.cljs
=> Fix tag sorting by :tag/order

projects/behave/src/cljs/behave/components/input_group.cljs
=> Actually fix tags order

projects/behave/resources/config.standalone.edn, projects/behave/src/cljs/behave/client.cljs, projects/behave/src/cljs/behave/components/toolbar.cljs
=> Remove VMS sync on JAR

projects/behave/resources/public/css/app-style.css
=> [BHP1-1271] Fix Footer hiding "Next" button

.github/workflows/jar-builder.yml
-------
Prevent JAR signing to avoid using DigiCert signatures
EOM
=> Remove Digicert JAR signing

bases/behave_components/src/cljs/behave/components/inputs.cljs, bases/behave_components/src/cljs/behave/stories/multi_select_input_stories.cljs, development/migrations/2025_07_08_add_multi_select_prompt_translations.clj, projects/behave/src/cljs/behave/components/input_group.cljs
-------
Closes BHP1-1350
1. Create Surface worksheet in standard view
2. Navigate to inputs > Fuel Model
3. Ensure the prompt is properly updated.
=> [BHP1-1350] Update Prompt for Multi Select Search Component

projects/behave/src/cljs/behave/worksheet/views.cljs
-------
Closes BHP1-1315
1. Ensure Mortality Only is not an option in the module selection page
=> [BHP1-1315] Hide Mortality Only

projects/behave/src/cljs/behave/wizard/views.cljs
-------
Closes BHP1-1302
1. Create and run a worksheet
2. Navigate to results and ensure the tab and the header for inputs have been updated
=> [BHP1-1302] Change the title in Results from "Input Tables" to "Inputs"

bases/behave_components/resources/public/css/styles.css
-------
Use default arrow in an html select element.
Closes BHP1-###
1. Ensure dropdown components look like this:
=> [BHP1-1318] Update Dropdown Arrow

projects/behave/resources/public/css/app-style.css, projects/behave/src/cljs/behave/print/views.cljs, projects/behave/src/cljs/behave/wizard/views.cljs
-------
EOM
Closes BHP1-1399
1. Create a new worksheet (e.g. Surface)
2. Get to Review page, verify that Run Description has been removed
3. Get to Result page, verify that Run Description input exists. Enter
something into the new input.
4. Click print, and verify that Run Description exists in the Print view.
=> [BHP1-1399] Move Run Description to Results, Add to Print View
